In [2]:
import pandas as pd

In [3]:
my_series = pd.Series([32,54,213,543])

In [4]:
my_series

0     32
1     54
2    213
3    543
dtype: int64

In [5]:
my_series.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
my_series.values

array([ 32,  54, 213, 543])

In [7]:
my_series.sum()

842

In [8]:
my_series.max()

543

In [9]:
my_series.mean()

210.5

In [10]:
my_series * 3

0      96
1     162
2     639
3    1629
dtype: int64

In [11]:
my_series.sort_values()

0     32
1     54
2    213
3    543
dtype: int64

In [12]:
my_series.value_counts()

543    1
54     1
213    1
32     1
dtype: int64

In [13]:
eu_loans = pd.read_csv('data/eu_revolving_loans.csv', header=[1,2,3], index_col=0, skiprows=1)

In [14]:
eu_loans.head()

,Austria,Belgium,Cyprus,Germany,Estonia,Spain,Finland,France,Greece (GR),Ireland,Italy,Lithuania,Luxembourg,Latvia,Malta,Netherlands,Portugal,Slovenia,Slovakia,Euro area (changing composition)
Collection:,End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),Average of observations through period (A)
Period\Unit:,[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ]
2016Feb,4.20,8.09,6.13,8.85,16.38,11.03,6.41,6.00,8.18,10.40,6.07,9.60,7.24,21.58,6.79,5.83,15.28,6.80,13.86,7.36
2016Jan,4.17,8.05,6.13,8.83,16.41,10.85,6.44,6.10,8.19,9.91,6.07,9.58,7.10,21.51,6.82,5.81,15.41,6.79,13.97,7.35
2015Dec,3.99,8.21,6.16,8.69,16.32,10.49,6.40,5.86,8.22,10.37,5.91,9.45,6.96,21.59,6.84,5.88,15.16,6.65,13.72,7.23
2015Nov,4.09,8.20,6.15,8.82,16.37,10.73,6.49,6.18,8.30,9.11,6.12,9.53,6.88,21.67,6.78,5.97,15.32,6.79,14.10,7.37
2015Oct,4.10,8.40,6.16,8.89,16.42,10.86,6.52,6.15,8.34,9.29,6.11,9.40,7.08,21.74,6.78,5.93,15.55,6.74,14.12,7.41

In [15]:
eu_loans.shape

(194, 20)

In [16]:
eu_loans.min()

                                  Collection:                                 Period\Unit:
Austria                           End of period (E)                           [Percent per annum ]    3.99
Belgium                           End of period (E)                           [Percent per annum ]    7.67
Cyprus                            End of period (E)                           [Percent per annum ]    6.13
Germany                           End of period (E)                           [Percent per annum ]    8.69
Estonia                           End of period (E)                           [Percent per annum ]       -
Spain                             End of period (E)                           [Percent per annum ]    8.07
Finland                           End of period (E)                           [Percent per annum ]     6.4
France                            End of period (E)                           [Percent per annum ]    5.86
Greece (GR)                       End of period (E)                           [Percent per annum ]    8.18
Ireland                           End of period (E)                           [Percent per annum ]    7.34
Italy                             End of period (E)                           [Percent per annum ]    5.91
Lithuania                         End of period (E)                           [Percent per annum ]    3.48
Luxembourg                        End of period (E)                           [Percent per annum ]     3.1
Latvia                            End of period (E)                           [Percent per annum ]    4.45
Malta                             End of period (E)                           [Percent per annum ]     inf
Netherlands                       End of period (E)                           [Percent per annum ]    5.62
Portugal                          End of period (E)                           [Percent per annum ]     7.9
Slovenia                          End of period (E)                           [Percent per annum ]     inf
Slovakia                          End of period (E)                           [Percent per annum ]     inf
Euro area (changing composition)  Average of observations through period (A)  [Percent per annum ]    7.23
dtype: object

In [17]:
eu_loans.mode()

,Austria,Belgium,Cyprus,Germany,Estonia,Spain,Finland,France,Greece (GR),Ireland,Italy,Lithuania,Luxembourg,Latvia,Malta,Netherlands,Portugal,Slovenia,Slovakia,Euro area (changing composition)
Collection:,End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),Average of observations through period (A)
Period\Unit:,[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ]
0,8.5,11.22,7.81,10.36,-,12.96,6.67,10.74,14.48,13.06,8.65,4.81,5.25,6.38,6.78,7.94,8.1,-,-,10.33
1,NaN,NaN,NaN,10.38,NaN,13.01,9.13,12.03,NaN,NaN,NaN,NaN,5.49,7.13,NaN,NaN,NaN,7.66,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,13.15,9.15,NaN,NaN,NaN,NaN,NaN,NaN,8.45,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.69,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.31,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.94,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.99,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.38,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
eu_loans * 3

,Austria,Belgium,Cyprus,Germany,Estonia,Spain,Finland,France,Greece (GR),Ireland,Italy,Lithuania,Luxembourg,Latvia,Malta,Netherlands,Portugal,Slovenia,Slovakia,Euro area (changing composition)
Collection:,End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),End of period (E),Average of observations through period (A)
Period\Unit:,[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ],[Percent per annum ]
2016Feb,12.60,24.27,18.39,26.55,16.3816.3816.38,33.09,19.23,18.00,24.54,31.20,18.21,28.80,21.72,64.74,6.796.796.79,17.49,45.84,6.806.806.80,13.8613.8613.86,22.08
2016Jan,12.51,24.15,18.39,26.49,16.4116.4116.41,32.55,19.32,18.30,24.57,29.73,18.21,28.74,21.30,64.53,6.826.826.82,17.43,46.23,6.796.796.79,13.9713.9713.97,22.05
2015Dec,11.97,24.63,18.48,26.07,16.3216.3216.32,31.47,19.20,17.58,24.66,31.11,17.73,28.35,20.88,64.77,6.846.846.84,17.64,45.48,6.656.656.65,13.7213.7213.72,21.69
2015Nov,12.27,24.60,18.45,26.46,16.3716.3716.37,32.19,19.47,18.54,24.90,27.33,18.36,28.59,20.64,65.01,6.786.786.78,17.91,45.96,6.796.796.79,14.1014.1014.10,22.11
2015Oct,12.30,25.20,18.48,26.67,16.4216.4216.42,32.58,19.56,18.45,25.02,27.87,18.33,28.20,21.24,65.22,6.786.786.78,17.79,46.65,6.746.746.74,14.1214.1214.12,22.23
2015Sep,12.96,25.74,18.51,26.85,16.4416.4416.44,32.61,19.56,19.23,25.59,28.14,18.42,27.99,21.21,65.25,6.796.796.79,17.91,46.53,6.816.816.81,14.2114.2114.21,22.59
2015Aug,12.84,24.81,19.08,26.73,16.4016.4016.40,32.43,19.41,19.17,25.77,26.73,18.36,28.17,21.39,65.40,6.606.606.60,18.15,45.63,6.796.796.79,14.2614.2614.26,22.47
2015Jul,12.21,24.69,19.14,26.70,16.3716.3716.37,32.22,19.32,18.75,25.35,26.49,18.57,28.29,21.78,65.46,6.786.786.78,17.76,46.26,6.716.716.71,14.2114.2114.21,22.32
2015Jun,12.87,24.51,19.26,27.03,16.3616.3616.36,32.49,19.41,19.71,25.95,25.62,18.81,28.50,21.99,65.76,6.786.786.78,17.61,46.41,6.766.766.76,14.1514.1514.15,22.74
2015May,12.96,24.36,19.38,26.97,16.3316.3316.33,33.21,19.47,20.16,25.71,25.17,18.84,28.83,21.96,65.43,6.766.766.76,17.70,47.43,6.806.806.80,14.1414.1414.14,22.86
2015Apr,12.63,24.72,19.20,27.30,16.3116.3116.31,33.27,20.01,19.74,25.71,24.96,19.08,28.92,21.99,65.58,6.786.786.78,17.97,47.19,6.826.826.82,13.9713.9713.97,22.92
2015Mar,13.29,24.93,18.69,27.63,16.3216.3216.32,33.63,19.71,20.67,25.71,25.23,19.11,27.96,22.77,64.68,6.776.776.77,18.15,46.98,6.866.866.86,13.8913.8913.89,23.25
2015Feb,12.78,24.27,21.42,27.66,16.3216.3216.32,34.32,20.07,20.67,25.86,25.05,19.71,27.93,25.35,64.65,6.756.756.75,17.91,47.40,6.906.906.90,13.9613.9613.96,23.40
2015Jan,12.72,24.93,21.54,27.66,16.3216.3216.32,33.39,20.01,20.61,25.74,22.50,19.71,27.81,24.66,64.83,6.766.766.76,18.12,47.49,6.906.906.90,14.0014.0014.00,23.28
2014Dec,12.60,25.11,21.60,27.60,16.2616.2616.26,32.76,19.89,19.95,25.74,23.13,19.20,11.76,26.04,64.35,6.776.776.77,18.03,46.53,6.876.876.87,13.7513.7513.75,22.92
2014Nov,12.90,24.96,21.57,27.60,16.3516.3516.35,33.03,19.86,21.30,25.98,22.77,19.95,11.58,22.17,63.33,6.736.736.73,18.24,47.70,7.017.017.01,13.4013.4013.40,23.40
2014Oct,12.90,25.20,21.60,27.81,16.3616.3616.36,31.89,19.80,20.88,27.12,22.02,20.10,11.55,22.02,63.36,6.716.716.71,18.21,47.94,6.956.956.95,13.5713.5713.57,23.31
2014Sep,13.77,23.16,21.60,28.20,16.3916.3916.39,32.37,20.04,21.66,27.03,22.47,20.49,11.85,21.18,64.11,6.696.696.69,18.18,47.34,6.976.976.97,13.5913.5913.59,23.70
2014Aug,13.50,23.04,21.72,27.81,16.3016.3016.30,32.40,20.10,21.48,25.80,22.50,20.40,11.85,21.30,64.08,6.726.726.72,17.88,46.59,6.966.966.96,13.5813.5813.58,23.43
2014Jul,13.56,23.01,21.84,28.11,16.3016.3016.30,31.74,20.01,20.70,26.19,22.47,20.58,12.03,21.12,64.14,6.626.626.62,18.00,46.98,6.886.886.88,13.4513.4513.45,23.31
2014Jun,13.86,24.12,21.96,28.38,16.3616.3616.36,32.25,20.19,21.48,26.58,22.47,21.09,11.13,21.39,64.17,6.696.696.69,17.97,47.22,7.037.037.03,13.5513.5513.55,23.76
2014May,13.62,24.18,21.87,28.05,16.2916.2916.29,32.28,20.49,21.66,26.91,22.29,21.03,10.92,21.06,64.29,6.726.726.72,18.18,47.70,7.007.007.00,13.6113.6113.61,23.76
2014Apr,13.77,26.10,21.93,27.75,16.3816.3816.38,32.28,20.49,22.08,27.09,22.44,21.18,11.10,21.75,64.05,6.726.726.72,18.36,47.16,7.067.067.06,13.6913.6913.69,23.88
2014Mar,14.37,26.22,21.93,28.38,16.3916.3916.39,32.19,20.55,22.53,27.00,22.41,21.36,11.01,21.60,63.90,6.796.796.79,18.30,47.67,7.077.077.07,13.6613.6613.66,24.18
2014Feb,13.74,26.52,21.93,28.23,16.5116.5116.51,32.49,20.49,23.04,27.18,22.59,21.60,10.98,22.41,64.14,6.806.806.80,18.21,48.12,7.167.167.16,13.6413.6413.64,24.33
2014Jan,13.71,26.85,21.99,28.35,16.5216.5216.52,31.50,20.37,22.44,27.27,22.71,21.54,10.98,21.36,64.98,6.826.826.82,18.33,47.88,7.127.127.12,13.7213.7213.72,24.12
2013Dec,13.50,26.91,21.69,28.26,16.4716.4716.47,30.12,20.28,21.99,27.36,22.83,20.91,11.07,22.68,25.68,6.866.866.86,18.24,46.62,7.207.207.20,13.6513.6513.65,23.76
2013Nov,13.32,26.82,21.96,28.32,16.5316.5316.53,31.83,20.28,22.71,27.21,22.68,21.24,10.92,21.30,25.86,6.836.836.83,18.51,47.37,7.307.307.30,13.7213.7213.72,24.06
2013Oct,13.86,27.03,23.40,28.59,16.5316.5316.53,31.86,20.19,22.23,27.93,22.38,21.57,10.65,21.63,26.34,6.886.886.88,18.69,48.09,7.257.257.25,13.8113.8113.81,24.24
2013Sep,14.55,26.94,23.43,28.83,16.5416.5416.54,30.96,20.28,22.92,27.78,22.74,21.57,10.71,21.00,28.35,6.876.876.87,18.51,48.03,7.287.287.28,13.8813.8813.88,24.39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2002Jun,25.50,33.66,NaN,32.88,---,39.48,30.27,36.15,47.73,39.18,27.72,NaN,NaN,NaN,NaN,23.82,25.20,NaN,NaN,32.40
2002May,25.50,33.66,NaN,32.76,---,39.45,30.39,36.09,47.82,39.18,27.57,NaN,NaN,NaN,NaN,23.82,25.20,NaN,NaN,32.28
2002Apr,25.50,33.66,NaN,32.76,---,39.51,30.45,36.09,47.79,39.18,27.60,NaN,NaN,NaN,NaN,23.82,23.70,NaN,NaN,32.22
2002Mar,25.59,33.66,NaN,32.46,---,39.30,30.00,35.55,47.64,39.18,27.63,NaN,NaN,NaN,NaN,23.82,24.30,NaN,NaN,31.98
2002Feb,25.62,33.66,NaN,32.61,---,39.45,29.94,35.55,47.70,39.18,27.72,NaN,NaN,NaN,NaN,23.82,25.50,NaN,NaN,32.07
2002Jan,25.50,33.66,NaN,32.67,---,39.15,30.33,35.55,47.64,39.18,27.72,NaN,NaN,NaN,NaN,23.82,25.80,NaN,NaN,32.07
2001Dec,25.68,33.66,NaN,32.70,---,39.81,30.45,35.34,46.17,39.18,27.84,NaN,NaN,NaN,NaN,23.82,27.60,NaN,NaN,32.19
2001Nov,25.83,33.78,NaN,32.88,---,39.60,30.75,35.31,46.38,39.18,28.53,NaN,NaN,NaN,NaN,23.82,30.00,NaN,NaN,32.43
2001Oct,25.95,34.74,NaN,33.12,---,39.75,31.44,35.31,46.71,40.53,29.16,NaN,NaN,NaN,NaN,26.79,31.20,NaN,NaN,32.91
2001Sep,26.07,35.31,NaN,33.21,---,39.66,31.83,36.09,47.49,41.73,29.55,NaN,NaN,NaN,NaN,26.79,29.70,NaN,NaN,33.12
2001Aug,26.43,37.41,NaN,33.57,---,39.72,33.15,36.09,47.25,42.72,29.67,NaN,NaN,NaN,NaN,31.26,30.60,NaN,NaN,33.69
2001Jul,26.37,37.86,NaN,33.51,---,39.57,33.36,36.09,47.19,42.72,29.79,NaN,NaN,NaN,NaN,31.26,31.80,NaN,NaN,33.75
2001Jun,26.22,37.86,NaN,33.72,---,39.45,33.45,36.84,47.28,42.72,29.88,NaN,NaN,NaN,NaN,31.26,30.30,NaN,NaN,33.90
2001May,26.49,37.86,NaN,33.36,---,39.51,33.84,36.87,48.24,42.72,30.09,NaN,NaN,NaN,NaN,31.26,32.40,NaN,NaN,33.87
2001Apr,26.49,37.86,NaN,33.72,---,39.45,34.05,36.87,49.32,43.23,30.15,NaN,NaN,NaN,NaN,32.76,32.10,NaN,NaN,34.11
2001Mar,26.52,37.80,NaN,33.66,---,39.39,34.29,36.27,49.56,43.23,30.18,NaN,NaN,NaN,NaN,32.76,32.40,NaN,NaN,33.99
2001Feb,26.52,37.86,NaN,33.75,---,39.39,34.20,36.27,51.27,43.23,30.27,NaN,NaN,NaN,NaN,32.76,33.00,NaN,NaN,34.08
2001Jan,26.61,37.86,NaN,33.99,---,39.54,34.47,36.27,51.57,43.23,30.39,NaN,NaN,NaN,NaN,32.76,32.10,NaN,NaN,34.17
2000Dec,26.49,37.89,NaN,33.63,---,38.79,34.17,35.43,53.40,43.23,30.48,NaN,NaN,NaN,NaN,32.76,32.40,NaN,NaN,33.93
2000Nov,27.15,37.89,NaN,33.81,---,38.79,34.44,35.43,54.00,43.14,30.69,NaN,NaN,NaN,NaN,32.76,30.30,NaN,NaN,33.96
2000Oct,27.36,36.81,NaN,33.51,---,38.61,34.47,35.43,54.63,43.02,30.60,NaN,NaN,NaN,NaN,32.76,30.30,NaN,NaN,33.75
2000Sep,27.21,36.81,NaN,32.76,---,38.67,34.05,35.07,55.17,42.00,29.94,NaN,NaN,NaN,NaN,31.26,28.80,NaN,NaN,33.12
2000Aug,27.18,36.81,NaN,32.64,---,39.03,33.96,35.10,55.77,41.79,29.28,NaN,NaN,NaN,NaN,29.76,29.40,NaN,NaN,32.91
2000Jul,27.00,34.71,NaN,32.58,---,39.03,33.27,35.10,55.98,41.79,29.34,NaN,NaN,NaN,NaN,29.76,30.90,NaN,NaN,32.85
2000Jun,27.36,34.65,NaN,31.50,---,38.85,33.09,33.12,57.75,40.71,28.80,NaN,NaN,NaN,NaN,29.76,28.50,NaN,NaN,32.04
2000May,27.18,34.65,NaN,30.75,---,39.06,32.49,33.09,58.05,39.24,28.08,NaN,NaN,NaN,NaN,26.79,28.20,NaN,NaN,31.32
2000Apr,26.97,32.46,NaN,30.63,---,39.03,31.62,33.09,61.38,39.24,27.54,NaN,NaN,NaN,NaN,25.32,27.60,NaN,NaN,30.99
2000Mar,26.70,31.44,NaN,30.06,---,38.88,31.47,32.76,62.61,38.52,27.15,NaN,NaN,NaN,NaN,25.32,27.30,NaN,NaN,30.48
2000Feb,26.79,30.42,NaN,29.88,---,38.85,31.05,32.73,63.66,37.59,26.91,NaN,NaN,NaN,NaN,23.82,27.30,NaN,NaN,30.27
2000Jan,26.49,30.03,NaN,29.43,---,38.88,30.84,32.73,64.86,37.59,26.64,NaN,NaN,NaN,NaN,22.32,27.00,NaN,NaN,29.94